import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Copy,
  Check,
  FileDown,
  Loader2,
} from 'lucide-react';
import type { BenefitsAnalysis } from '../types';

interface ExportBarProps {
  analysis: BenefitsAnalysis;
  fileName: string;
}

function buildSummaryText(analysis: BenefitsAnalysis, fileName: string): string {
  const lines: string[] = [];
  lines.push('BENEFITLENS AI — DOCUMENT ANALYSIS SUMMARY');
  lines.push('==========================================');
  lines.push(`File: ${fileName}`);
  lines.push(`Document Type: ${analysis.documentType}`);
  lines.push(`Plan Type: ${analysis.planType}`);
  lines.push('');
  lines.push('SUMMARY');
  lines.push('-------');
  lines.push(analysis.summary);
  lines.push('');

  const sections: [string, string[]][] = [
    ['KEY DEADLINES', analysis.keyDeadlines],
    ['IMPORTANT DATES', analysis.importantDates],
    ['COVERAGE', analysis.coverage],
    ['EMPLOYEE RESPONSIBILITIES', analysis.employeeResponsibilities],
    ['EMPLOYER RESPONSIBILITIES', analysis.employerResponsibilities],
    ['IMPORTANT WARNINGS', analysis.importantWarnings],
    ['NEXT STEPS', analysis.nextSteps],
  ];

  for (const [title, items] of sections) {
    lines.push(title);
    lines.push('-'.repeat(title.length));
    if (items.length === 0) {
      lines.push('  None identified.');
    } else {
      items.forEach((item, i) => lines.push(`  ${i + 1}. ${item}`));
    }
    lines.push('');
  }

  if (analysis.commonQuestions.length > 0) {
    lines.push('COMMON QUESTIONS');
    lines.push('----------------');
    analysis.commonQuestions.forEach((qa, i) => {
      lines.push(`  Q${i + 1}: ${qa.question}`);
      lines.push(`  A: ${qa.answer}`);
      lines.push('');
    });
  }

  lines.push('==========================================');
  lines.push('Generated by BenefitLens AI');
  return lines.join('\n');
}

function buildPrintableHTML(analysis: BenefitsAnalysis, fileName: string): string {
  const section = (title: string, items: string[]) => `
    <div class="section">
      <h2>${title}</h2>
      ${items.length === 0 ? '<p class="empty">None identified.</p>' : `<ul>${items.map((item) => `<li>${item}</li>`).join('')}</ul>`}
    </div>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>BenefitLens AI — Analysis Summary</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; padding: 48px; background: #fff; }
    .header { border-bottom: 3px solid #00a3f5; padding-bottom: 20px; margin-bottom: 32px; }
    .header h1 { font-size: 28px; color: #0a4974; margin-bottom: 4px; }
    .header .subtitle { font-size: 14px; color: #64748b; }
    .meta { display: flex; gap: 24px; margin-bottom: 32px; }
    .meta-item { background: #f0f9ff; border-radius: 8px; padding: 12px 20px; }
    .meta-item .label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
    .meta-item .value { font-size: 16px; font-weight: 700; color: #0a4974; }
    .summary { background: #f8fafc; border-radius: 12px; padding: 24px; margin-bottom: 32px; }
    .summary h2 { font-size: 18px; color: #0a4974; margin-bottom: 12px; }
    .summary p { font-size: 14px; line-height: 1.6; color: #334155; }
    .section { margin-bottom: 24px; }
    .section h2 { font-size: 16px; color: #0a4974; margin-bottom: 10px; padding-bottom: 6px; border-bottom: 1px solid #e2e8f0; }
    .section ul { list-style: none; }
    .section li { font-size: 13px; line-height: 1.6; color: #334155; padding: 4px 0 4px 20px; position: relative; }
    .section li:before { content: '→'; position: absolute; left: 0; color: #06c8a3; font-weight: 700; }
    .empty { font-size: 13px; color: #94a3b8; font-style: italic; }
    .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <h1>BenefitLens AI — Document Analysis</h1>
    <div class="subtitle">Understand Employee Benefits Documents in Seconds</div>
  </div>
  <div class="meta">
    <div class="meta-item">
      <div class="label">File</div>
      <div class="value">${fileName}</div>
    </div>
    <div class="meta-item">
      <div class="label">Document Type</div>
      <div class="value">${analysis.documentType}</div>
    </div>
    <div class="meta-item">
      <div class="label">Plan Type</div>
      <div class="value">${analysis.planType}</div>
    </div>
  </div>
  <div class="summary">
    <h2>Summary</h2>
    <p>${analysis.summary}</p>
  </div>
  ${section('Key Deadlines', analysis.keyDeadlines)}
  ${section('Important Dates', analysis.importantDates)}
  ${section('Coverage', analysis.coverage)}
  ${section('Employee Responsibilities', analysis.employeeResponsibilities)}
  ${section('Employer Responsibilities', analysis.employerResponsibilities)}
  ${section('Important Warnings', analysis.importantWarnings)}
  ${section('Next Steps', analysis.nextSteps)}
  <div class="footer">Generated by BenefitLens AI</div>
</body>
</html>`;
}

export function ExportBar({ analysis, fileName }: ExportBarProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  const handleCopy = async () => {
    const text = buildSummaryText(analysis, fileName);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback
    }
  };

  const handleExportPDF = () => {
    setExporting(true);
    const html = buildPrintableHTML(analysis, fileName);
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      setTimeout(() => {
        printWindow.print();
        setExporting(false);
      }, 500);
    } else {
      setExporting(false);
    }
  };

  return (
    <div className="flex flex-wrap items-center gap-3">
      <motion.button
        whileHover={{ scale: 1.03 }}
        whileTap={{ scale: 0.97 }}
        onClick={handleCopy}
        className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white border border-slate-200 text-sm font-semibold text-slate-700 hover:border-primary-300 hover:text-primary-700 transition-all"
      >
        <AnimatePresence mode="wait">
          {copied ? (
            <motion.span key="copied" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2">
              <Check className="w-4 h-4 text-teal-500" />
              Copied!
            </motion.span>
          ) : (
            <motion.span key="copy" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex items-center gap-2">
              <Copy className="w-4 h-4" />
              Copy Summary
            </motion.span>
          )}
        </AnimatePresence>
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.03 }}
        whileTap={{ scale: 0.97 }}
        onClick={handleExportPDF}
        disabled={exporting}
        className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-primary-600 to-teal-500 text-white text-sm font-semibold shadow-lg shadow-primary-600/20 disabled:opacity-60"
      >
        {exporting ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Preparing...
          </>
        ) : (
          <>
            <FileDown className="w-4 h-4" />
            Export PDF
          </>
        )}
      </motion.button>
    </div>
  );
}
